language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "RLY0jiij1VWc7+DY0113bqE56pDLNf7dp4c3K1+uKQLJLQK4/cr2TcVPxo5Ve7YGurdO78wAo6d5cbT1kc8AQ8ChwCTDDsJExZEvCinB3/vM5FJyOzaZ2w7T/Gt5RpA7bWQ/CnkwbcYznohwJbmOyz7GCLS6O5rCKZyRzeVEjkyGhUz0cty67oeJ2NR5GzT5T0K459q1m8RUvpaRfMg4QrlhQVPwR3wB78rLhuBGXgStRmg5eamRvOPWNPo5LJiHpD6KxPK9/yXH0asPyIUoFi5lwMPhzwkRh8hcfC6pHqO3gcBC1kuyb9u0EguWhYCARRMFX/0H72icAmspTDXry1KSTUyw6S11tdqavapHtZm53u8TeRp+CBpztk9c2WALNPhjKBs+Okr8PL33BXHZ6a0I6k6kK5NeuFik/5glbV6rkdK+rEuxEpgDooSiCNQEodjW+aXyBGUf60PI3I+b/UCrof/8YxcOtrsK3mVuThYPh78tdqmpkaIZ0Ca6BLghlbU9G7zMrEQOBS+KHKbkoD24D96E5FoIN3o2ZaMlhOZlXmed9T00jZe1JEeUqZe2uc6Pw/h56Y0pikZubxqFMkjLLKpnH7ZWWpx4oAe7Vtmup8c7KP+prtY4Z/estlgI/+Ss4mind5RcmpZJG/8nebLuKZ3J4w1QY3qGwSviKwI="
